flows:
  - summary: IGM
    id: igm-flow
    createSessionAtBuyer: true
    domain: ONDC:RET10
    shouldDispaly: true
    sessionData:
      on_status: true
      dualmode: true
      currency: INR
      subscriber_url: https://igm-mock-service.ondc.org/igm-protocol-server-preprod/ondc
      subscriber_id: igm-mock-service.ondc.org/igm-protocol-server-preprod
      resolutions_object: []
      actorsKey:
        - id: NP2
          type: COUNTERPARTY_NP
          info:
            org:
              name: sellerapp.com::ONDC:RET10
            contact:
              phone: '9450394140'
              email: respondentapp@respond.com
            person:
              name: Jane Doe
      info_requested:
        - INFO0001
        - INFO0002
        - INFO0003
      resolutions:
        REFUND:
          id: R1
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: REFUND
            short_desc: Providing refund for the item
          updated_at: "2024-08-14T09:57:58.841Z"
          proposed_by: NP2
          tags:
            - descriptor:
                code: RESOLUTION_DETAILS
              list:
                - descriptor:
                    code: ITEM
                  value: I1
                - descriptor:
                    code: REFUND_AMOUNT
                  value: "200"

        REPLACEMENT:
          id: R2
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: REPLACEMENT
            short_desc: Providing replacement of the item
          updated_at: "2024-08-14T09:57:58.841Z"
          proposed_by: NP2
          tags:
            - descriptor:
                code: RESOLUTION_DETAILS
              list:
                - descriptor:
                    code: ITEM
                  value: I1

        CANCEL:
          id: R3
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: CANCEL
            short_desc: Cancelling the order/item
          updated_at: "2024-08-14T10:00:00.000Z"
          proposed_by: NP2
          tags:
            - descriptor:
                code: RESOLUTION_DETAILS
              list:
                - descriptor:
                    code: ITEM
                  value: I1
                - descriptor:
                    code: CANCEL_REASON
                  value: Customer requested cancellation

        NO_ACTION:
          id: R4
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: NO_ACTION
            short_desc: No action will be taken on this item
          updated_at: "2024-08-14T10:01:00.000Z"
          proposed_by: NP2

        NOW_VISIBLE:
          id: R5
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: NOW_VISIBLE
            short_desc: Item is now visible to the customer
          updated_at: "2024-08-14T10:02:00.000Z"
          proposed_by: NP2

        RECONCILED:
          id: R6
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: RECONCILED
            short_desc: This item has been reconciled
          updated_at: "2024-08-14T10:03:00.000Z"
          proposed_by: NP2
          tags:
            - descriptor:
                code: RESOLUTION_DETAILS
              list:
                - descriptor:
                    code: ITEM
                  value: I1
                - descriptor:
                    code: STATUS
                  value: Reconciled successfully

        NOT_RECONCILED:
          id: R7
          ref_id: R_PARENT
          ref_type: PARENT
          descriptor:
            code: NOT_RECONCILED
            short_desc: Item could not be reconciled
          updated_at: "2024-08-14T10:04:00.000Z"
          proposed_by: NP2
          tags:
            - descriptor:
                code: RESOLUTION_DETAILS
              list:
                - descriptor:
                    code: ITEM
                  value: I1
                - descriptor:
                    code: STATUS
                  value: Pending reconciliation

    protocol:
      $ref: ./igm-flow/protocolMapping.yaml#/protocol
    calls:
      $ref: ./igm-flow/calls.yaml#/calls
    api:
      issue:
        default:
          service_url: http://localhost:5501/mapper/ondc
          sync: false
    ui: true

  - summary: IGM
    id: igm-reverse-flow
    createSessionAtBuyer: true
    dualmode: true
    domain: ONDC:RET10
    shouldDispaly: true
    sessionData:
      closed_tags:
        - descriptor:
            code: CLOSURE_DETAILS
          list:
          - descriptor:
              code: RATING
            value: THUMBS_UP
      on_status: true
      currency: INR
      dualmode: true
      subscriber_url: https://igm-mock-service.ondc.org/igm-protocol-server-preprod/ondc
      subscriber_id: igm-mock-service.ondc.org/igm-protocol-server-preprod
      issueId: "ISSUE-1"
      issueStatus: "OPEN"
      issuelevel: "ISSUE"
      expected_response_time:
        duration: "PT2H"
      expected_resolution_time:
        duration: "P1D"
      item_tags:
        - descriptor:
            code: "message.order.items"
          list:
            - descriptor:
                code: "quantity.selected.count"
              value: "2"
      actors:
        - id: "CUST1"
          type: "CONSUMER"
          info:
            org:
              name: "igm-mock-service.ondc.org::ONDC:RET10"
            person:
              name: "Sam Manuel"
            contact:
              phone: "9879879870"
              email: "sam@yahoo.com"
        - id: "NP1"
          type: "INTERFACING_NP"
          info:
            org:
              name: "igm-mock-service.ondc.org::ONDC:RET10"
            contact:
              phone: "9450394039"
              email: "igm-mock-service.ondc.org@interface.com"
            person:
              name: "John Doe"
      sourceId: "CUST1"
      complainantId: "NP1"
      descriptor:
        code: "ITM004"
        short_desc: "Issue with product quality"
        long_desc: "Product quality is not correct. facing issues while using the product"
        additional_desc:
          url: "https://igm-mock-service.ondc.org.com/additonal-details/desc.txt"
          content_type: "text/plain"
        images:
        -  url:  "http://igm-mock-service.ondc.org.com/addtional-details/img1.png"
      lastactionid: "A1"
      action_id: "A1"
      resolution_keys_proposed:
        id: A9
        ref_id: R_PARENT
        ref_type: RESOLUTIONS
        descriptor:
          code: RESOLUTION_PROPOSED
        updated_at: "2023-01-15T10:00:00.469Z"
        action_by: NP2
        actor_details:
            name: Sam Manuel
      actions_descriptor:
        code: "OPEN"
        short_desc: "Complaint created"
      actor_details:
        name: "Sam Manuel"
      action_append: []
      actions: []

    protocol:
      $ref: ./igm-reverse-flow/protocolMapping.yaml#/protocol
    calls:
      $ref: ./igm-reverse-flow/calls.yaml#/calls
    api:
      issue:
        default:
          service_url: http://localhost:5501/mapper/ondc
          sync: false
    ui: true

flow_selector:
  issue:
    default:
      config_id: "igm-flow"
    igm-flow:
      condition:
        operation:
          type: AND
          input:
            value:
              - operation:
                  type: EQUAL
                  title: Check settlement type message code
                  input:
                    value:
                      - operation:
                          type: READ
                          input:
                            value: "req_body.message.issue.descriptor.code"
                      - "ITM004"
      config_id: "igm-flow"

  on_issue:
    default:
      config_id: "igm-reverse-flow"

  session-builder:
    default:
      config_id: "igm-reverse-flow"
